### PR TITLE
Intermediate Bootloader

### PR DESCRIPTION
**Pull request by naveenspace7**
Intermediate bootloader to upgrade the legacy bootloader to secure bootloader along with the Softdevice. The process has been described in intermediate/README.md

### CODE REVIEW

**Review by vliedel — CHANGES_REQUESTED** [review]
Hi Naveen,

Nice to see progression. A few points that need to be fixed:
- Instructions how to build the intermediate bootloader.
- A description of what the phone side should do, including checks to be performed.
- Testing on a crownstone, I think you will find that suddenly you run into some errors, like the BUTTONS_NUMBER.
- Setting the output pins that control the IGBTs and relay, this is important to do.
- Don't use hard coded addresses in the code, like 0x79000.

**Comment by naveenspace7** [comment]
* Added instructions on the build process.
* Removed hardcoded values.
* Tested on a crownstone.

**Comment by vliedel** [comment]
Hey,

I think it's good if you'd do a comparison between the files in the (original) top dir and the intermediate dir. I found a few things that are different, for example the advertised bluetooth address being changed in the intermediate bootloader.

The led pin numbers are still hard coded in the gpio functions.
The build process requires you to edit files for the different intermediate bootloaders. To avoid human mistakes, you should make this automated. You could have different targets in the makefile for example. Also add scripts or make targets to generate the dfu package.

The inner workings aren't documented yet. I think that's necessary in order to fully review this pull request.

**Comment by naveenspace7** [comment]
* Added a flowchart for the internal details.
* Brought back the changes that were left out from v1.3.0.
* Automated the build and pack process.

**Comment by vliedel** [comment]
Did a full review of the code now, I'm going to merge it, but some comments:

- [dfu_dual_bank.c:373](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L373)
  - Should check for a certain max size.

- [entrance_check()](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L777)
  - Not used.

- [flash_page_erase(uint32_t * p_page)](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L753)
  - Assumes `p_page` is start of page.
  - From where is this implementation?

- [erase_pages(uint32_t page_addr, const uint32_t size_words)](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L797)
  - Assumes `page_addr` is start of page.
  - Uses `0x400` instead of `(CODE_PAGE_SIZE / 4)`.
  - From where is this implementation?

- [copy_flash_content(uint32_t * const dest_addr, uint32_t const * const src_addr, uint32_t size_bytes)](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L812)
  - Assumes size_bytes is multiple of 4.
  - From where is this implementation?

- [set_uicr()](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L837)
  - Add comment: copies all UICR values to ram, erases UICR, then writes from ram to UICR again.
  - Taken from [post](https://devzone.nordicsemi.com/f/nordic-q-a/18199/dfu---updating-from-legacy-sdk-v11-0-0-bootloader-to-secure-sdk-v12-x-0-bootloader)
  - Why was `nrf_delay_ms(100)` added?

- [dfu_relocate_bl()](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L1039)
  - Same as `dfu_bl_image_swap()`, only `BL_ADDR = INT_BL_ADDR` instead of `NEW_BL_ADDR`.

- [dfu_dual_bank.c:715](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L715)
  - Add comment: makes block_size a multiple of `CODE_PAGE_SIZE` as in [this post](https://devzone.nordicsemi.com/f/nordic-q-a/16774/updating-from-s132-v2-0-x-to-s132-v3-0-0-with-dual-bank-bootloader-from-sdk-v11-0-0-does-not-work/64161#64161)

- [dfu_bl_image_swap()](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L916)
  - Change compared to example: `copy_flash_content(NEW_BL_ADDR, bl_image_start, bootloader_settings.bl_image_size)` instead of `sd_mbr_command(SD_MBR_COMMAND_COPY_BL, bl_image_start, bootloader_settings.bl_image_size / 4)`
  - Taken from [post](https://devzone.nordicsemi.com/f/nordic-q-a/18199/dfu---updating-from-legacy-sdk-v11-0-0-bootloader-to-secure-sdk-v12-x-0-bootloader)

- [dfu_bl_image_validate()](https://github.com/naveenspace7/bluenet-bootloader/blob/4a66839d05bfcd556f6d2f497b8d126314f650cf/intermediate/src/dfu_dual_bank.c#L951)
  - Change compared to example: `bank_1_region` depends on `BOOTLOADER_REGION_START`, using `find_bank_1_region(BOOTLOADER_REGION_START)`.

**Comment by naveenspace7** [comment]
1. The previous maximum value was ignored in the given solution. But we can add the new binary image (size of secure bootloader) size there, only then the secure bootloader can be copied. I can bring back the logic, its value has to be fixed (I am not sure of the exact size of the new image).

2. Removed "entrance_check()"

3. There is a function "ble_flash_page_erase()" (which later calls "flash_page_erase()") in "ble_flash.c" (present in nRF-SDK-11). That is the same exact function I copied. And yes it expects the start of the page address. (I wanted to avoid copying another file from the SDK just for this function)

4. I found it on Stackoverflow, added the source link there. If basically ceils any fractional number of pages to 1. Example: 1536 (1 and a half page) would be 2 pages.

5. Added the source of the logic.

6. Added link. During the initial days, I saw that the flash values weren't updated. Suspecting that it could be fixed by a delay, I added the delay and I saw the desired behavior. Now that I think of it 100ms can be reduced to a lower value.

7. Reused dfu_bl_image_swap() function by passing it an arg.

8. Added post in comments.

9. Added relevant explanation why function "copy_flash_content()" is neccessary in the function comments.

10. Yes, I had written a small explanation for why this change is required. Do you feel that the explanation is not sufficient?

**Comment by vliedel** [comment]
Thanks for the effort! I was just hoping for you to answer the questions, didn't expect you to fix and commit :)
6. 100 ms is fine, I just didn't see any delay in nordics post, so was wondering why it was added.
10. Was more of a note, I wrote notes for everything that was changed.

**Pull request merged**
